name: Trigger Build

on:
  push:
    branches:
      - main  # or whichever branches you want to monitor

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger container rebuild
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PUBLIC_REPO_SYNC_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Cian-H/my_nvim/dispatches \
            -d '{"event_type":"rebuild-container","client_payload":{"repository":"${{ github.repository }}"}}'
