name: Trigger Container Rebuild

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/CianH/my_nvim/dispatches \
             -f "event_type=on-demand-test" -F "client_payload[unit]=false" -F "client_payload[integration]=true"
